<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>be1ac683-2a90-4d33-a24b-5857e8c0d16c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MudBlazor" Version="9.*" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\src\Core\WoodOps.Contracts\WoodOps.Contracts.csproj" />
    <ProjectReference Include="..\src\Infrastructure\WoodOps.Runtime\WoodOps.Runtime.csproj" />
  </ItemGroup>
</Project>