<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\WoodOps.Domain\WoodOps.Domain.csproj" />
    <ProjectReference Include="..\WoodOps.Contracts\WoodOps.Contracts.csproj" />
  </ItemGroup>
  <PropertyGroup></PropertyGroup>
</Project>