<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WoodOps.Domain\WoodOps.Domain.csproj" />
    <ProjectReference Include="..\WoodOps.Contracts\WoodOps.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
