<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d2c06862-de18-4678-b3ca-c1bc40470f46</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\WoodOps.Application\WoodOps.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\WoodOps.Persistence\WoodOps.Persistence.csproj" />
    <ProjectReference Include="..\..\Infrastructure\WoodOps.Cache\WoodOps.Cache.csproj" />
    <ProjectReference Include="..\..\Infrastructure\WoodOps.Messaging\WoodOps.Messaging.csproj" />
    <ProjectReference Include="..\..\Infrastructure\WoodOps.Observability\WoodOps.Observability.csproj" />
    <ProjectReference Include="..\..\Infrastructure\WoodOps.Runtime\WoodOps.Runtime.csproj" />
  </ItemGroup>

</Project>
