<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\WoodOps.Persistence\WoodOps.Persistence.csproj" />
    <ProjectReference Include="..\..\Infrastructure\WoodOps.Messaging\WoodOps.Messaging.csproj" />
    <ProjectReference Include="..\..\Infrastructure\WoodOps.Storage\WoodOps.Storage.csproj" />
  </ItemGroup>
  <PropertyGroup></PropertyGroup>
</Project>